
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  host: localhost
  database: myrecepeis_development
  
test:
  <<: *default
  host: localhost
  database: myrecepeis_test

production:
  <<: *default
  database: myrecepeis_production